# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_pergunta.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_perguntas(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1640, 924)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imag_perguntas/icone_padrao.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.Tela_fundo = QtWidgets.QLabel(Dialog)
        self.Tela_fundo.setGeometry(QtCore.QRect(0, 0, 1651, 931))
        self.Tela_fundo.setStyleSheet("background-image: url(:/imag_perguntas/Quiz G-SEPi (1).png);")
        self.Tela_fundo.setText("")
        self.Tela_fundo.setObjectName("Tela_fundo")
        self.Botao_A1 = QtWidgets.QPushButton(Dialog)
        self.Botao_A1.setGeometry(QtCore.QRect(240, 390, 391, 101))
        self.Botao_A1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 38, 38);\n"
"border-color: rgb(38, 38, 38);\n"
"border-color: rgb(38, 38, 38);\n"
"font: 22pt \"Noto Sans Lisu\"")
        self.Botao_A1.setAutoDefault(False)
        self.Botao_A1.setFlat(True)
        self.Botao_A1.setObjectName("Botao_A1")
        self.Botao_A2 = QtWidgets.QPushButton(Dialog)
        self.Botao_A2.setGeometry(QtCore.QRect(970, 390, 391, 101))
        self.Botao_A2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 38, 38);\n"
"border-color: rgb(38, 38, 38);\n"
"border-color: rgb(38, 38, 38);\n"
"font: 22pt \"Noto Sans Lisu\";")
        self.Botao_A2.setAutoDefault(False)
        self.Botao_A2.setFlat(True)
        self.Botao_A2.setObjectName("Botao_A2")
        self.Botao_A3 = QtWidgets.QPushButton(Dialog)
        self.Botao_A3.setGeometry(QtCore.QRect(240, 600, 391, 101))
        self.Botao_A3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 38, 38);\n"
"border-color: rgb(38, 38, 38);\n"
"border-color: rgb(38, 38, 38);\n"
"font: 22pt \"Noto Sans Lisu\";")
        self.Botao_A3.setAutoDefault(False)
        self.Botao_A3.setFlat(True)
        self.Botao_A3.setObjectName("Botao_A3")
        self.Botao_A4 = QtWidgets.QPushButton(Dialog)
        self.Botao_A4.setGeometry(QtCore.QRect(970, 600, 391, 101))
        self.Botao_A4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 38, 38);\n"
"border-color: rgb(38, 38, 38);\n"
"border-color: rgb(38, 38, 38);\n"
"font: 22pt \"Noto Sans Lisu\";")
        self.Botao_A4.setAutoDefault(False)
        self.Botao_A4.setFlat(True)
        self.Botao_A4.setObjectName("Botao_A4")
        self.Pergunta = QtWidgets.QLabel(Dialog)
        self.Pergunta.setGeometry(QtCore.QRect(390, 150, 5341, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Lisu")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Pergunta.setFont(font)
        self.Pergunta.setStyleSheet("font: 28pt \"Noto Sans Lisu\";")
        self.Pergunta.setObjectName("Pergunta")
        self.Score = QtWidgets.QLabel(Dialog)
        self.Score.setGeometry(QtCore.QRect(760, 770, 111, 51))
        self.Score.setStyleSheet("\n"
"font: 87 32pt \"Source Code Pro Black\";\n"
"")
        self.Score.setObjectName("Score")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.tentativa = 0
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Quiz G-SEPi: Perguntas"))
        self.Botao_A1.setText(_translate("Dialog", "Alternativa 1"))
        self.Botao_A2.setText(_translate("Dialog", "Alternativa 2"))
        self.Botao_A3.setText(_translate("Dialog", "Alternativa 3"))
        self.Botao_A4.setText(_translate("Dialog", "Alternativa 4"))
        self.Pergunta.setText(_translate("Dialog", "Pergunta 1"))
        self.Score.setText(_translate("Dialog", "10"))
from res_tela_perguntas import tela_perguntas_res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_perguntas()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
