# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_instrucoes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_instrucoes(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(820, 462)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imag_login/icone_padrao.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 831, 471))
        self.label.setStyleSheet("background-image: url(:/imag_login/4.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_iNSTRUCOES = QtWidgets.QLabel(Dialog)
        self.label_iNSTRUCOES.setGeometry(QtCore.QRect(310, 80, 201, 51))
        self.label_iNSTRUCOES.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Noto Sans Lisu\";")
        self.label_iNSTRUCOES.setObjectName("label_iNSTRUCOES")
        self.label_iNSTRUCOES_2 = QtWidgets.QLabel(Dialog)
        self.label_iNSTRUCOES_2.setGeometry(QtCore.QRect(170, 170, 491, 61))
        self.label_iNSTRUCOES_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Noto Sans Lisu\";")
        self.label_iNSTRUCOES_2.setObjectName("label_iNSTRUCOES_2")
        self.label_iNSTRUCOES_3 = QtWidgets.QLabel(Dialog)
        self.label_iNSTRUCOES_3.setGeometry(QtCore.QRect(130, 200, 491, 61))
        self.label_iNSTRUCOES_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Noto Sans Lisu\";")
        self.label_iNSTRUCOES_3.setObjectName("label_iNSTRUCOES_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Quiz G-SEPi: Instruções"))
        self.label_iNSTRUCOES.setText(_translate("Dialog", "INSTRUÇÕES"))
        self.label_iNSTRUCOES_2.setText(_translate("Dialog", "O Quiz possui 4 perguntas objetivas, basta clicar"))
        self.label_iNSTRUCOES_3.setText(_translate("Dialog", "no botão começar na tela de início e..."))
from res_tela_login import login_res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_instrucoes()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
